### ISSUE TITLE
Deal correctly with missing config file

### ISSUE THREAD

**Issue by onekiloparsec** [arcsecond-io/oort#2]
With an absent `.oort/` folder, here we have:

```
cedricfoellmi@server-oes:~$ oort restart
2020-11-22 14:38:18,112 - oort-cloud - INFO - Stopping Oort processes...
Error: could not find config file /home/cedricfoellmi/.oort/supervisord.conf
For help, use /home/cedricfoellmi/.local/bin/supervisorctl -h
Error: could not find config file /home/cedricfoellmi/.oort/supervisord.conf
For help, use /home/cedricfoellmi/.local/bin/supervisorctl -h
2020-11-22 14:38:18,370 - oort-cloud - INFO - Stopping supervisord...
Traceback (most recent call last):
  File "/home/cedricfoellmi/.local/bin/oort", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cedricfoellmi/.local/lib/python3.7/site-packages/oort/cli/cli.py", line 135, in restart
    stop_supervisor_daemon(debug=state.debug)
  File "/home/cedricfoellmi/.local/lib/python3.7/site-packages/oort/cli/supervisor.py", line 148, in stop_supervisor_daemon
    pidfile = conf.get('supervisord', 'pidfile').split(';')[0].strip()
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'supervisord'
```

**Comment by onekiloparsec** [comment]
Fixed.
